name: Build and Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-18.04  # Changed to ubuntu-18.04 for older GLIBC
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Using an even older Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask yt-dlp pyinstaller

    - name: Create temp resources directory
      run: |
        mkdir -p temp_resources
        cp -r templates temp_resources/
        cp -r static temp_resources/

    - name: Build with PyInstaller
      run: |
        python -m PyInstaller --onefile \
          --name "yt-dluxe" \
          --add-data "temp_resources/templates:templates" \
          --add-data "temp_resources/static:static" \
          --clean \
          --noconsole \
          app.py

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/yt-dluxe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true